openapi: 3.0.1
tags:
  - name: facility
  - name: robot
  - name: map
  - name: waypoint
  - name: path
  - name: owner
  - name: rawRobot
info:
  title: RaaSWebAPIv2
  version: '1.0'
  contact:
    name: onClouds
  description: rass APiv2
servers:
  - url: 'http://localhost:3000'
paths:
  /maps:
    get:
      summary: Your GET endpoint
      tags:
        - map
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  pagenate:
                    $ref: ../models/common/pagenateTemplate.v1.json
                  data:
                    type: array
                    items:
                      $ref: ../models/mapMeta.v2.json
                required:
                  - pagenate
                  - data
      operationId: getMaps
      parameters:
        - schema:
            type: string
          in: query
          name: search
          description: 検索文字列
        - schema:
            type: number
          in: query
          name: page
          description: ページ数
        - schema:
            type: number
          in: query
          name: limit
          description: 表示数
      description: 地図一覧を取得
    parameters: []
    post:
      summary: add a new map
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/mapMeta.v2.json
      description: 新規に地図を登録する
      operationId: createMap
      tags:
        - map
      requestBody:
        content:
          application/json:
            schema:
              type: object
              title: createMapType
              properties:
                param:
                  $ref: ../models/mapParams.v2.json
                pgm:
                  type: string
                  description: バイナリ型のpgmファイル
                  format: binary
              required:
                - param
                - pgm
        description: ''
  '/maps/{mapId}':
    description: mapの取得
    get:
      summary: get MapMeta
      tags:
        - map
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/mapMeta.v2.json
      operationId: getMap
      description: Idを指定してMapの取得
    parameters:
      - schema:
          type: string
        name: mapId
        in: path
        required: true
    delete:
      summary: ''
      operationId: deleteMap
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
      description: map 削除
      tags:
        - map
    put:
      summary: update a map
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/mapMeta.v2.json
      description: 地図の内容を変更
      parameters: []
      operationId: updateMap
      tags:
        - map
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/mapParams.v2.json
        description: ''
  '/maps/{mapId}/pgm':
    parameters:
      - schema:
          type: string
        name: mapId
        in: path
        required: true
    get:
      summary: get pgm url
      tags:
        - map
      responses:
        '200':
          description: OK
      operationId: getPGMmapURL
      description: 詳細説明なし
    put:
      summary: ''
      operationId: putPGMmap
      responses:
        '200':
          description: OK
      tags:
        - map
      description: 詳細説明なし
  '/maps/{mapId}/cost':
    parameters:
      - schema:
          type: string
        name: mapId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags:
        - map
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                pattern: '^(http|https)://([\w-]+\.)+[\w-]+(/[\w-./?%&=]*)?$'
                readOnly: true
              examples:
                '0000000000000001':
                  value: 'http://localhost:3000/resource/bitmap/chinokyoten1f.png'
                '0000000000000002':
                  value: 'http://localhost:3000/resource/bitmap/chinokyoten2f.png'
                '0000000000000003':
                  value: 'http://localhost:3000/resource/bitmap/chinokyoten3f.png'
      operationId: getCostmapURL
      description: mapIdで指定される画像(PNG)を取得可能なURLが返る
    put:
      summary: ''
      operationId: putCostmap
      responses:
        '200':
          description: OK
      description: 詳細説明なし
      tags:
        - map
  /facilities:
    get:
      summary: GET Facilities
      tags:
        - facility
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  pagenate:
                    $ref: ../models/common/pagenateTemplate.v1.json
                  data:
                    type: array
                    items:
                      $ref: ../models/facility.json
              examples:
                example-1:
                  value:
                    pagenate:
                      current_page: 1
                      from: 1
                      to: 1
                      first_page_url: string
                      last_page_url: string
                      next_page_url: string
                      prev_page_url: string
                      path: string
                      last_page: 1
                      per_page: 100
                      total: 1
                    data:
                      - id: '0000000000000001'
                        registDate: '1964-02-02T18:25:36.294Z'
                        updateDate: '2019-11-20T16:31:46.928Z'
                        name: chinokyoten
                        countOfFloor: 3
                        floors:
                          - id: fl-1
                            translation:
                              x: '0'
                              'y': '0'
                              z: '0'
                            rotation:
                              roll: 0
                              pitch: 0
                              yaw: 0.8
                            floorNumber: 1
                            description: ''
                            maps:
                              - id: '0000000000000001'
                                name: map-1
                                description: ''
                                resolution: 0.05
                                negate: false
                                occupied_thresh: 0.65
                                free_thresh: 0.196
                                size:
                                  width: 4000
                                  height: 4000
                                owner:
                                  id: owner-1
                                  name: veniam
                                  owned_robot: []
                                  owned_map: []
                                  updateDate: '2019-11-20T16:31:46.928Z'
                                floor:
                                  id: fl-1
                                origin:
                                  x: -100
                                  'y': -100
                                  z: 0
                                rotation:
                                  roll: 0
                                  pitch: 0
                                  yaw: 1.75
                                updateDate: '2019-11-20T16:31:46.928Z'
                                pgm_link: 'http://hogehoge.com/hoge'
                                gen_preSingnedUrl: 'http://hogehoge.com/hoge'
                            waypoints: []
                          - id: fl-2
                            translation:
                              x: '0'
                              'y': '0'
                              z: '0'
                            rotation:
                              roll: 0
                              pitch: 0
                              yaw: 0
                            floorNumber: 2
                            description: ''
                            updateDate: '2019-11-20T16:31:46.928Z'
                            maps:
                              - id: '0000000000000002'
                                name: map-2
                                description: ''
                                resolution: 0.05
                                negate: false
                                occupied_thresh: 0.65
                                free_thresh: 0.196
                                size:
                                  width: 4000
                                  height: 4000
                                owner:
                                  id: owner-1
                                  name: veniam
                                  owned_robot: []
                                  owned_map: []
                                  updateDate: '2019-11-20T16:31:46.928Z'
                                floor:
                                  id: fl-2
                                origin:
                                  x: -100
                                  'y': -80
                                  z: 0
                                rotation:
                                  roll: 0
                                  pitch: 0
                                  yaw: 0
                                updateDate: '2019-11-20T16:31:46.928Z'
                                pgm_link: 'http://hogehoge.com/hoge'
                                gen_preSingnedUrl: 'http://hogehoge.com/hoge'
                            waypoints: []
                          - id: fl-3
                            translation:
                              x: '0'
                              'y': '0'
                              z: '0'
                            rotation:
                              roll: 0
                              pitch: 0
                              yaw: 0
                            floorNumber: 3
                            description: ''
                            updateDate: '2019-11-20T16:31:46.928Z'
                            maps:
                              - id: '0000000000000003'
                                name: map-3
                                description: ''
                                resolution: 0.05
                                negate: false
                                occupied_thresh: 0.65
                                free_thresh: 0.196
                                size:
                                  width: 4000
                                  height: 4000
                                owner:
                                  id: owner-1
                                  name: veniam
                                  owned_robot: []
                                  owned_map: []
                                  updateDate: '2019-11-20T16:31:46.928Z'
                                floor:
                                  id: fl-3
                                origin:
                                  x: -130
                                  'y': -70
                                  z: 0
                                rotation:
                                  roll: 0
                                  pitch: 0
                                  yaw: 0
                                pgm_link: 'http://hogehoge.com/hoge'
                                gen_preSingnedUrl: 'http://hogehoge.com/hoge'
                            waypoints: []
        '201':
          description: Created
      operationId: getFacilities
      description: 詳細説明なし
    parameters: []
    post:
      summary: post facility
      operationId: createFacility
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/facility.json
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/facilityParams.v1.json
      description: Facilityの作成
      tags:
        - facility
  '/facilities/{facilityId}':
    parameters:
      - schema:
          type: string
        name: facilityId
        in: path
        required: true
    get:
      summary: get Facility
      tags:
        - facility
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/facility.json
      operationId: getFacility
      description: 詳細説明なし
    delete:
      summary: ''
      operationId: deleteFacility
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
      description: facilityの削除
      tags:
        - facility
    put:
      summary: Update a Facility
      operationId: updateFacility
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/facility.json
      description: facilityの更新
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/facilityParams.v1.json
      tags:
        - facility
  /waypoints:
    get:
      summary: get waypoints
      tags:
        - waypoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  pagenate:
                    $ref: ../models/common/pagenateTemplate.v1.json
                  data:
                    type: array
                    items:
                      $ref: ../models/waypoint.v2.json
                required:
                  - pagenate
                  - data
              examples:
                example-1:
                  value:
                    pagenate:
                      current_page: 1
                      from: 0
                      to: 0
                      first_page_url: string
                      last_page_url: string
                      next_page_url: string
                      prev_page_url: string
                      path: string
                      last_page: 0
                      per_page: 1
                      total: 0
                    data:
                      - id: '0000000000000101'
                        name: Entrance
                        facility:
                          id: '0000000000000001'
                        owner:
                          id: '0001000000000001'
                          name: owner-1
                          owned_robot: []
                          owned_map: []
                        floor: 1
                        point:
                          x: -5.5
                          'y': 23.1
                          z: 0
                        attributes:
                          - attribute1
                      - id: '0000000000000105'
                        name: floor01-2
                        facility:
                          id: '0000000000000001'
                        owner:
                          id: '0001000000000001'
                          name: owner-1
                          owned_robot: []
                          owned_map: []
                        floor: 1
                        point:
                          x: -21.8
                          'y': 43
                          z: 0
                        attributes:
                          - attribute1
                      - id: '0000000000000102'
                        name: Laboratory
                        facility:
                          id: '0000000000000001'
                        owner:
                          id: '0001000000000001'
                          name: owner-1
                          owned_robot: []
                          owned_map: []
                        floor: 2
                        point:
                          x: -20
                          'y': 14.4
                          z: 0
                        attributes:
                          - attribute2
                      - id: '0000000000000106'
                        name: floor2-2
                        facility:
                          id: '0000000000000001'
                        owner:
                          id: '0001000000000001'
                          name: owner-1
                          owned_robot: []
                          owned_map: []
                        action:
                          - string
                        floor: 2
                        point:
                          x: -2
                          'y': -4.6
                          z: 0
                        attributes:
                          - attribute2
                      - id: '0000000000000103'
                        name: test1
                        facility:
                          id: '0000000000000001'
                        owner:
                          id: '0001000000000001'
                          name: owner-1
                          owned_robot: []
                          owned_map: []
                        action:
                          - action2
                        floor: 3
                        point:
                          x: 18.8
                          'y': -28.8
                          z: 0
                        attributes:
                          - attribute1
                          - attribute2
                      - id: '0000000000000107'
                        name: floor3-2
                        facility:
                          id: '0000000000000001'
                        owner:
                          id: '0001000000000001'
                          name: owner-1
                          owned_robot: []
                          owned_map: []
                        floor: 3
                        point:
                          x: 10
                          'y': -2.2
                          z: 0
                        attributes:
                          - attribute1
                          - attribute2
                      - id: '0000000000000104'
                        name: center
                        facility:
                          id: '0000000000000002'
                        owner:
                          id: '0001000000000001'
                          name: owner-1
                          owned_robot: []
                          owned_map: []
                        floor: 2
                        point:
                          x: 0
                          'y': 0
                          z: 0
                        attributes: []
      operationId: getWaypoints
      description: waypointの一覧を取得
      parameters:
        - schema:
            type: integer
          in: query
          name: page
        - schema:
            type: integer
          in: query
          name: limit
    post:
      summary: add new waypoint
      operationId: createWaypoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/waypoint.v2.json
              examples: {}
      description: waypointの追加
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/waypointParams.v2.json
            examples: {}
      tags:
        - waypoint
  '/waypoints/{waypointID}':
    parameters:
      - schema:
          type: string
        name: waypointID
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags:
        - waypoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/waypoint.v2.json
      operationId: getWaypoint
      description: 指定されたwaypointIDのwaypointを返す
      parameters: []
    put:
      summary: ''
      operationId: updateWaypoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/waypoint.v2.json
      description: waypoint 変更
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/waypointParams.v2.json
      tags:
        - waypoint
    delete:
      summary: ''
      operationId: deleteWaypoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
      description: waypointの削除
      tags:
        - waypoint
  /autopath:
    post:
      summary: get auto generate path
      responses:
        '200':
          description: |-
            OK
            methodは'move'で返ってくる
          content:
            application/json:
              schema:
                $ref: ../models/roboOperation.json
              examples:
                example-1:
                  value:
                    method: move
                    robotSpecifications:
                      - id: '0000000000000001'
                    argment:
                      - floor: 0
                        point:
                          x: 15.12
                          'y': 0.635
                          z: 0
                        attributes: []
                      - floor: 0
                        point:
                          x: -5.5
                          'y': 23.1
                          z: 0
                        attributes:
                          - attribute1
                      - floor: 0
                        point:
                          x: -21.8
                          'y': 43
                          z: 0
                        attributes:
                          - attribute1
                      - floor: 1
                        point:
                          x: -20
                          'y': 14.4
                          z: 0
                        attributes:
                          - attribute2
                      - floor: 1
                        point:
                          x: -2
                          'y': -4.6
                          z: 0
                        attributes:
                          - attribute1
                      - floor: 2
                        point:
                          x: 18.8
                          'y': -28.8
                          z: 0
                        attributes:
                          - attribute1
                      - floor: 2
                        point:
                          x: 10
                          'y': -2.2
                          z: 0
                        attributes:
                          - attribute1
      description: 自動生成したpathを取得
      operationId: generatePath
      requestBody:
        content:
          application/json:
            schema:
              type: object
              title: GeneratePathType
              description: waypoint array
              properties:
                points:
                  type: array
                  items:
                    $ref: ../models/common/floorAttribute.json
                algorithms:
                  type: array
                  items:
                    $ref: ../models/pathAlgorithm.v1.json
                robot:
                  type: object
                  required:
                    - specification
                  properties:
                    specification:
                      $ref: ../models/common/idObject.v1.json
              required:
                - points
                - algorithms
                - robot
            examples: {}
        description: ''
      tags:
        - path
      parameters:
        - schema:
            type: string
          in: query
          name: facility_id
          description: Pathを生成するfacilityのID
  /owners:
    get:
      summary: Your GET endpoint
      tags:
        - owner
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  pagenate:
                    $ref: ../models/common/pagenateTemplate.v1.json
                  data:
                    type: array
                    items:
                      $ref: ../models/owner.v1.json
              examples:
                example-1:
                  value:
                    pagenate:
                      current_page: 0
                      from: 0
                      to: 0
                      first_page_url: string
                      last_page_url: string
                      next_page_url: string
                      prev_page_url: string
                      path: string
                      last_page: 0
                      per_page: 1
                      total: 0
                    data:
                      - id: '0001000000000001'
                        name: sample owner
                        owned_robot:
                          - string
                        owned_map:
                          - string
      operationId: getOwners
      description: Ownerの一覧を取得
      parameters:
        - schema:
            type: integer
          in: query
          name: page
        - schema:
            type: integer
          in: query
          name: limit
  /me:
    get:
      summary: Your GET endpoint
      tags:
        - owner
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/owner.v1.json
              examples:
                example-1:
                  value:
                    id: '0001000000000001'
                    name: sample owner
                    owned_robot:
                      - string
                    owned_map:
                      - string
      operationId: getMeInfo
      description: Ownerの一覧を取得
      parameters: []
    parameters: []
  /paths:
    get:
      summary: get all paths
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  pagenate:
                    $ref: ../models/common/pagenateTemplate.v1.json
                  data:
                    type: array
                    items:
                      $ref: ../models/path.v1.json
              examples:
                example-1:
                  value:
                    data:
                      - id: 0123456789aaaaaa
                        name: path-1
                        facility:
                          id: '0000000000000001'
                        operations:
                          - method: move
                            arguments:
                              - floor: 1
                                point:
                                  x: -18.69999999999999
                                  'y': 26.400000000000006
                                  z: 0
                                attributes: []
                              - floor: 1
                                point:
                                  x: 12
                                  'y': 15
                                  z: 0
                                attributes: []
                        owner:
                          id: 0123456789aaabbb
                      - id: '0000000000000001'
                        name: path-01212
                        facility:
                          id: '0000000000000001'
                        operations:
                          - method: move
                            arguments:
                              - floor: 1
                                point:
                                  x: -2.4499999999999886
                                  'y': 4.3500000000000085
                                  z: 0
                                attributes: []
                              - floor: 1
                                point:
                                  x: 11.5
                                  'y': -5
                                  z: 0
                                attributes: []
                        owner:
                          id: 0123456789aaabbb
                      - id: '0000000000000003'
                        name: path-03
                        facility:
                          id: '0000000000000001'
                        operations:
                          - method: move
                            arguments:
                              - floor: 1
                                point:
                                  x: -85.5
                                  'y': 4.35
                                  z: 0
                                attributes: []
                              - floor: 1
                                point:
                                  x: 61.5
                                  'y': 4
                                  z: 0
                                attributes: []
                        owner:
                          id: 0123456789aaabbb
                      - id: '0000000000000004'
                        name: path-04
                        facility:
                          id: '0000000000000001'
                        operations:
                          - method: move
                            arguments:
                              - floor: 1
                                point:
                                  x: -85.5
                                  'y': -85.35
                                  z: 0
                                attributes: []
                              - floor: 1
                                point:
                                  x: 61.5
                                  'y': 64
                                  z: 0
                                attributes: []
                        owner:
                          id: 0123456789aaabbb
      operationId: getPaths
      description: pathの一覧を取得
      tags:
        - path
      parameters:
        - schema:
            type: integer
          in: query
          name: page
        - schema:
            type: integer
          in: query
          name: limit
    post:
      summary: add new path
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/path.v1.json
      description: pathの追加
      operationId: createPath
      tags:
        - path
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/pathParams.v1.json
  '/paths/{pathID}':
    parameters:
      - schema:
          type: string
        name: pathID
        in: path
        required: true
    get:
      summary: get a Path
      tags:
        - path
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/path.v1.json
      operationId: getPath
      description: Pathの取得
    put:
      summary: update a path
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/path.v1.json
      description: Pathの変更
      operationId: updatePath
      tags:
        - path
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/pathParams.v1.json
    delete:
      summary: delete a path
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
      description: Pathの削除
      operationId: deletePath
      tags:
        - path
  '/robots/{robotID}':
    parameters:
      - schema:
          type: string
        name: robotID
        in: path
        required: true
    get:
      summary: get one robot info
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/robot.v1.json
      description: |
        ロボットDBレコード取得
        get one robot DB record
      parameters: []
      operationId: getRobot
      tags:
        - robot
    put:
      summary: update a robot
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/robot.v1.json
      description: |-
        ロボットDB変更
        update robot DB
      parameters: []
      operationId: updateRobot
      tags:
        - robot
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/robotParams.v1.json
        description: ''
    delete:
      summary: delete a robot
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
      description: |-
        ロボットDB削除
        delete a robot form robot DB
      operationId: deleteRobot
      tags:
        - robot
  /robots:
    get:
      summary: get robots
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  pagenate:
                    $ref: ../models/common/pagenateTemplate.v1.json
                  data:
                    type: array
                    items:
                      $ref: ../models/robot.v1.json
              examples:
                example-1:
                  value:
                    pagenate:
                      current_page: 1
                      from: 1
                      to: 0
                      first_page_url: string
                      last_page_url: string
                      next_page_url: string
                      prev_page_url: string
                      path: string
                      last_page: 0
                      per_page: 0
                      total: 0
                    data:
                      - id: '0000000000000001'
                        name: Chinokyoten_Elevator
                        type: elevator
                        specification:
                          id: ef150538-268d-404d-acf4-78c2b2749dd3
                          type: elevator
                          discription: Chinokyoten Elevator
                          manufacturer: TOSHIBA
                          MQTT: true
                          webRTC: false
                          size:
                            width: 2
                            height: 3
                            depth: 2
                          supportSpecs:
                            - type: navigation
                              manufacturer: TOSHIBA
                              MQTT: true
                              webRTC: false
                              size:
                                width: 2
                                height: 3
                                depth: 2
                        home:
                          id: e739c2d0-ed0a-404a-8b2b-0c9968746c66
                          name: elevator1f
                          floor: 1
                          point:
                            z: 0
                            x: 1007
                            'y': 960
                          owner:
                            id: af8719c1-28ed-4e8a-937f-73e65d143515
                            name: onclouds
                            owned_map:
                              - 39ff8a0d-66dc-4dec-a525-1d258f9a120a
                              - 3ca13748-2958-4928-b10b-b31feca5439d
                              - fb346dce-fb84-4709-8c5e-76e339949af8
                            owned_robot:
                              - 0c6acbd8-6b87-4d67-a2a3-8bbe3192fd53
                              - d083b7bd-6910-497f-8d15-3cc2cf7e3fca
                          attributes:
                            - elevator
                          facility:
                            id: dummyId
                        stopWaypoints:
                          - id: 3a7d8fc3-31d0-46fd-a3b5-c475b1f18ce1
                            name: elevator2f
                            floor: 2
                            point:
                              z: 0
                              x: 1034
                              'y': 1368
                            owner:
                              id: af8719c1-28ed-4e8a-937f-73e65d143515
                              name: onclouds
                              owned_map:
                                - 39ff8a0d-66dc-4dec-a525-1d258f9a120a
                                - 3ca13748-2958-4928-b10b-b31feca5439d
                                - fb346dce-fb84-4709-8c5e-76e339949af8
                              owned_robot:
                                - 0c6acbd8-6b87-4d67-a2a3-8bbe3192fd53
                                - d083b7bd-6910-497f-8d15-3cc2cf7e3fca
                            attributes:
                              - elevator
                            facility:
                              id: dummyId
                          - id: 711a0a6b-2472-42a5-b8ca-960912627beb
                            name: elevator3f_wp
                            floor: 3
                            point:
                              z: 0
                              x: 383
                              'y': 1317
                            owner:
                              id: af8719c1-28ed-4e8a-937f-73e65d143515
                              name: onclouds
                              owned_map:
                                - 39ff8a0d-66dc-4dec-a525-1d258f9a120a
                                - 3ca13748-2958-4928-b10b-b31feca5439d
                                - fb346dce-fb84-4709-8c5e-76e339949af8
                              owned_robot:
                                - 0c6acbd8-6b87-4d67-a2a3-8bbe3192fd53
                                - d083b7bd-6910-497f-8d15-3cc2cf7e3fca
                            attributes:
                              - wp
                            facility:
                              id: dummyId
                          - id: d3e0fede-d485-4049-9b42-d3122b098dbd
                            name: elevator2f_wp
                            floor: 2
                            point:
                              z: 0
                              x: 1063
                              'y': 1349
                            owner:
                              id: af8719c1-28ed-4e8a-937f-73e65d143515
                              name: onclouds
                              owned_map:
                                - 39ff8a0d-66dc-4dec-a525-1d258f9a120a
                                - 3ca13748-2958-4928-b10b-b31feca5439d
                                - fb346dce-fb84-4709-8c5e-76e339949af8
                              owned_robot:
                                - 0c6acbd8-6b87-4d67-a2a3-8bbe3192fd53
                                - d083b7bd-6910-497f-8d15-3cc2cf7e3fca
                            attributes:
                              - wp
                            facility:
                              id: dummyId
                          - id: e739c2d0-ed0a-404a-8b2b-0c9968746c66
                            name: elevator1f
                            floor: 1
                            point:
                              z: 0
                              x: 1007
                              'y': 960
                            owner:
                              id: af8719c1-28ed-4e8a-937f-73e65d143515
                              name: onclouds
                              owned_map:
                                - 39ff8a0d-66dc-4dec-a525-1d258f9a120a
                                - 3ca13748-2958-4928-b10b-b31feca5439d
                                - fb346dce-fb84-4709-8c5e-76e339949af8
                              owned_robot:
                                - 0c6acbd8-6b87-4d67-a2a3-8bbe3192fd53
                                - d083b7bd-6910-497f-8d15-3cc2cf7e3fca
                            attributes:
                              - elevator
                            facility:
                              id: dummyId
                          - id: e906d295-c8a6-4a87-bfb4-5ddfba2676f7
                            name: elevator3f
                            floor: 3
                            point:
                              z: 0
                              x: 370
                              'y': 1285
                            owner:
                              id: af8719c1-28ed-4e8a-937f-73e65d143515
                              name: onclouds
                              owned_map:
                                - 39ff8a0d-66dc-4dec-a525-1d258f9a120a
                                - 3ca13748-2958-4928-b10b-b31feca5439d
                                - fb346dce-fb84-4709-8c5e-76e339949af8
                              owned_robot:
                                - 0c6acbd8-6b87-4d67-a2a3-8bbe3192fd53
                                - d083b7bd-6910-497f-8d15-3cc2cf7e3fca
                            attributes:
                              - elevator
                            facility:
                              id: dummyId
                          - id: ef934197-95da-43bc-9b1a-2bd785e7ae20
                            name: elevator1f_wp
                            floor: 1
                            point:
                              z: 0
                              x: 1031
                              'y': 995
                            owner:
                              id: af8719c1-28ed-4e8a-937f-73e65d143515
                              name: onclouds
                              owned_map:
                                - 39ff8a0d-66dc-4dec-a525-1d258f9a120a
                                - 3ca13748-2958-4928-b10b-b31feca5439d
                                - fb346dce-fb84-4709-8c5e-76e339949af8
                              owned_robot:
                                - 0c6acbd8-6b87-4d67-a2a3-8bbe3192fd53
                                - d083b7bd-6910-497f-8d15-3cc2cf7e3fca
                            attributes:
                              - wp
                            facility:
                              id: dummyId
                        facility:
                          id: dummyId
                        owner:
                          id: af8719c1-28ed-4e8a-937f-73e65d143515
                          name: onclouds
                          owned_map:
                            - 39ff8a0d-66dc-4dec-a525-1d258f9a120a
                            - 3ca13748-2958-4928-b10b-b31feca5439d
                            - fb346dce-fb84-4709-8c5e-76e339949af8
                          owned_robot:
                            - 0c6acbd8-6b87-4d67-a2a3-8bbe3192fd53
                            - d083b7bd-6910-497f-8d15-3cc2cf7e3fca
                      - id: '0000000000000002'
                        name: talbot_green
                        type: navigation
                        specification:
                          id: f4a707c4-a815-45f9-b964-abdc11fa9e83
                          name: talbot
                          type: navigation
                          manufacturer: Shinmei
                          MQTT: true
                          webRTC: false
                          discription: SHINMEI talbot
                          size:
                            width: 0.8
                            height: 0.8
                            depth: 0.8
                          radius: 0.4
                          max_speed: 0.6
                          max_acceleration: 0.6
                          max_angular_speed: 1
                        home:
                          id: 4badea5c-42e1-482d-8914-27a2fabf6fc8
                          name: hoge_waypoint
                          floor: 1
                          point:
                            z: 3
                            x: 1
                            'y': 2
                          owner:
                            id: af8719c1-28ed-4e8a-937f-73e65d143515
                            name: onclouds
                            owned_map:
                              - 39ff8a0d-66dc-4dec-a525-1d258f9a120a
                              - 3ca13748-2958-4928-b10b-b31feca5439d
                              - fb346dce-fb84-4709-8c5e-76e339949af8
                            owned_robot:
                              - 0c6acbd8-6b87-4d67-a2a3-8bbe3192fd53
                              - d083b7bd-6910-497f-8d15-3cc2cf7e3fca
                          attributes:
                            - home
                          facility:
                            id: dummyId
                        facility:
                          id: dummyId
                        owner:
                          id: af8719c1-28ed-4e8a-937f-73e65d143515
                          name: onclouds
                          owned_map:
                            - 39ff8a0d-66dc-4dec-a525-1d258f9a120a
                            - 3ca13748-2958-4928-b10b-b31feca5439d
                            - fb346dce-fb84-4709-8c5e-76e339949af8
                          owned_robot:
                            - 0c6acbd8-6b87-4d67-a2a3-8bbe3192fd53
                            - d083b7bd-6910-497f-8d15-3cc2cf7e3fca
      description: |-
        ロボットDB一覧取
        get all robot DB record

        絞り込みはbodyで
        TODO: ページング
      parameters:
        - schema:
            type: number
            default: 1
          in: query
          name: page
        - schema:
            type: number
          in: query
          name: limit
        - schema:
            type: string
          in: query
          name: sort
        - schema:
            type: string
            enum:
              - elevator
              - navigation
          in: query
          name: type
        - schema:
            type: string
          in: query
          name: facility
      operationId: getRobots
      tags:
        - robot
    post:
      summary: add a new robot
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/robot.v1.json
      operationId: createRobot
      description: |-
        ロボットDB追加
        add new robot to robot DB
      tags:
        - robot
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/robotParams.v1.json
  '/rawRobot/{robotID}':
    parameters:
      - schema:
          type: string
        name: robotID
        in: path
        required: true
    get:
      summary: get robot infos
      description: |-
        現在のロボット情報取得
        get robot infomation
      operationId: getRawRobot
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/rawRobot.v1.json
              examples:
                '0000000000000001':
                  value:
                    id: '0000000000000001'
                    since: '2020-01-01T01:01:01Z'
                    IP: 100.100.100.001
                    floor: 1
                    point:
                      x: 7
                      'y': -35
                      z: 0
                    ang:
                      roll: 0
                      pitch: 0
                      yaw: 0
                    battery: 50
                '0000000000000002':
                  value:
                    id: '0000000000000002'
                    since: '2020-01-01T01:01:01Z'
                    IP: 100.100.100.002
                    floor: 2
                    point:
                      x: 0
                      'y': 0
                      z: 0.5
                    ang:
                      roll: 0
                      pitch: 0
                      yaw: 0
                    battery: 80
                '0000000000000003':
                  value:
                    id: '0000000000000003'
                    since: '2019-08-24T14:15:22Z'
                    IP: 100.100.100.003
                    battery: 20
                    floor: 3
                    point:
                      x: -2
                      'y': -15
                      z: 0
                    ang:
                      roll: 0
                      pitch: 0
                      yaw: 0
      tags:
        - rawRobot
  '/robotTypes/{robotType_id}':
    parameters:
      - schema:
          type: string
        name: robotType_id
        in: path
        required: true
  /robotSpecification:
    get:
      summary: getRobotSpecification
      tags:
        - robot
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  pagenate:
                    $ref: ../models/common/pagenateTemplate.v1.json
                  data:
                    type: array
                    items:
                      $ref: ../models/robotSpecification.json
              examples:
                example-1:
                  value:
                    pagenate:
                      current_page: 0
                      from: 0
                      to: 0
                      first_page_url: string
                      last_page_url: string
                      next_page_url: string
                      prev_page_url: string
                      path: string
                      last_page: 0
                      per_page: 1
                      total: 0
                    data:
                      - id: nav-1
                        manufacturer: manufact-1
                        type: navigation
                        MQTT: true
                        webRTC: true
                        discription: string
                        size:
                          height: 10
                          width: 10
                          depth: 10
                        name: nav-1 name
                        radius: 2
                        max_speed: 0
                        max_acceleration: 0
                        max_angular_speed: 0
                      - id: el-1
                        manufacturer: manufact-2
                        type: elevator
                        MQTT: true
                        webRTC: false
                        discription: string
                        size:
                          height: 10
                          width: 10
                          depth: 10
                        name: elevator-1 name
                        radius: 2
                        max_speed: 0
                        max_acceleration: 0
                        max_angular_speed: 0
      operationId: getRobotSpecifications
    parameters: []
  '/robotSpecification/{robotModel_id}':
    parameters:
      - schema:
          type: string
        name: robotModel_id
        in: path
        required: true
    get:
      summary: getRobotSpecification
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/robotSpecification.json
      operationId: getRobotSpecification
      tags:
        - robot
  '/sendOperation/{robot_id}':
    parameters:
      - schema:
          type: string
        name: robot_id
        in: path
        required: true
    post:
      summary: sendOperation
      tags:
        - rawRobot
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
      operationId: operateRobot
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: ../models/roboOperation.json
components:
  schemas: {}
  responses: {}
  parameters:
    map_id:
      name: map_id
      in: path
      required: true
      schema:
        type: string
        example: '0000000000000013'
        minLength: 16
        maxLength: 16
        pattern: '[0-9]{16}'
    page:
      name: page
      in: query
      required: false
      schema:
        type: integer
        format: int32
        minimum: 1
        default: 1
      description: ページ数
    limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        format: int32
        default: 100
        minimum: 1
        maximum: 300
      description: 表示数
    facility_id:
      name: facility_id
      in: path
      required: true
      schema:
        type: string
      description: 施設のID
    elevator_id:
      name: elevator_id
      in: path
      required: true
      schema:
        type: string
      description: エレベーターのID
  examples:
    pgm_linkURL:
      value:
        description: Example shared example
        type: object
        properties:
          url:
            type: string
            example: 'http://localhost/pgmimage.pgm'
        required:
          - url
    costmap_linkURL:
      value:
        description: Example shared example
        type: object
        properties:
          url:
            type: string
            example: 'http://localhost/costmapimage.png'
        required:
          - url
